name: Tests (with e2e)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 5 * * 4"

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.24']
        os: [ubuntu-24.04 , ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    # https://github.com/testcontainers/testcontainers-go/pull/2482 until this is merged
    - name: Fetch required Docker Images
      run: docker pull alpine:3.22 && docker pull golang:1.24.5-alpine3.22

    - name: Run e2e tests
      run: cd tests/e2e && go test -v -race -coverprofile=coverage.out ./...
    
